version: '3.1'
services:
  postgres-1:
    container_name: postgres-1
    image: postgres:15.0
    environment:
      POSTGRES_USER: "postgresadmin"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "postgresdb"
      PGDATA: "/data"
    volumes:
      - ./postgres-1/pgdata:/data
      - ./postgres-1/config:/config
      - ./postgres-1/archive:/mnt/server/archive
    command: ["postgres", "-c", "config_file=/config/postgresql.conf"]
    ports:
      - 5000:5432
    networks:
      - postgres-network-replica
  
  # postgres-2:
  #   container_name: postgres-2
  #   image: postgres:15.0
  #   environment:
  #     POSTGRES_USER: "postgresadmin"
  #     POSTGRES_PASSWORD: "admin123"
  #     POSTGRES_DB: "postgresdb"
  #     PGDATA: "/data"
  #   volumes:
  #     - ./postgres-2/pgdata:/data
  #     - ./postgres-2/config:/config
  #     - ./postgres-2/archive:/mnt/server/archive
  #   command: ["postgres", "-c", "config_file=/config/postgresql.conf"]
  #   ports:
  #     - 5001:5432
  #   networks:
  #     - postgres-network
      
networks:
  postgres-network-replica: 
    driver: bridge