version: '3.1'
services:
  postgres-2:
    container_name: postgres-2
    image: postgres:15.0
    environment:
      POSTGRES_USER: "postgresadmin"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "postgresdb"
      PGDATA: "/data"
    volumes:
      - ./postgres-2/pgdata:/data
      - ./postgres-2/config:/config
      - ./postgres-2/archive:/mnt/server/archive
    command: ["postgres", "-c", "config_file=/config/postgresql.conf"]
    ports:
      # - 5001:5432
      - 5002:5432
    networks:
      - postgresql-replicate_postgres-network-replica

networks:
  postgresql-replicate_postgres-network-replica:
  # postgresql-replicate_postgres-network:
    external: true